-- ⚠️ حذف جميع البيانات (إبقاء الهيكل فقط)
-- شغّل هذا في Supabase SQL Editor

-- حذف البيانات بالترتيب الصحيح (يحترم Foreign Keys)
TRUNCATE TABLE audit_log RESTART IDENTITY CASCADE;
TRUNCATE TABLE payments RESTART IDENTITY CASCADE;
TRUNCATE TABLE invoices RESTART IDENTITY CASCADE;
TRUNCATE TABLE transactions RESTART IDENTITY CASCADE;
TRUNCATE TABLE financial_cycles RESTART IDENTITY CASCADE;
TRUNCATE TABLE worker_contracts RESTART IDENTITY CASCADE;
TRUNCATE TABLE customers RESTART IDENTITY CASCADE;
TRUNCATE TABLE expense_types RESTART IDENTITY CASCADE;
TRUNCATE TABLE services RESTART IDENTITY CASCADE;
TRUNCATE TABLE equipment RESTART IDENTITY CASCADE;
TRUNCATE TABLE equipment_types RESTART IDENTITY CASCADE;
TRUNCATE TABLE workers RESTART IDENTITY CASCADE;
TRUNCATE TABLE partners RESTART IDENTITY CASCADE;

-- تم تصفير جميع البيانات بنجاح ✓
