#!/bin/bash
echo "🔧 لإضافة البيئات إلى Vercel:"
echo ""
echo "1. اذهب إلى: https://vercel.com/dashboard"
echo "2. اختر project 'sharakh'"
echo "3. اذهب إلى Settings > Environment Variables"
echo "4. أضف هذه المتغيرات:"
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL=https://jwekgsjmcacbhunjudwi.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3ZWtnc2ptY2FjYmh1bmp1ZHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1MzgxMTEsImV4cCI6MjA5ODExNDExMX0.IlrvrQ-jHtBK3etjOYek60HhA7CBrEDX9d5eG29OpZ0"
echo "SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3ZWtnc2ptY2FjYmh1bmp1ZHdpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MjUzODExMSwiZXhwIjoyMDk4MTE0MTExfQ.QxAIZT_bLuE_Dzy-0RGG1pz47biznb0UaAlJVkUdnmU"
echo "JWT_SECRET=mK9\$xP2vL8nQ4rT7wY1uA6bC3dF5gH0jN"
echo "TELEGRAM_BOT_TOKEN=8746554281:AAFJml0g-awOotJSvjB3NfNxSyEv0Vvw_xU"
echo "TELEGRAM_BOT_USERNAME=SharakhPartnerBot"
echo "NEXT_PUBLIC_APP_URL=https://sharakh.vercel.app"
echo "SUPER_ADMIN_EMAILS=kkab1398@gmail.com"
echo "SUPER_ADMIN_SECRET_PATH=x7k9-panel-2024"
echo "CRON_SECRET=shr_cron_7k2mX9pL4nQ8vT1w"
echo ""
echo "5. اضغط 'Save'"
echo "6. سيتم redeploy تلقائياً"
